### ISSUE TITLE
Some minor documentation issues.

### ISSUE THREAD

**Issue by trickert76** [daniel-ness/ansible-vault#1]
Hi Daniel,

nice work. I'd helped me a lot to generate dynamic inventories with encrypted data.

You should update your README. 

- the encryption seems to work. A can encrypt/decrypt values with your lib and it works with Ansible
- the composer dependency is `ansible-vault` and not `vault-ansible`.

With best regards
Thoralf

**Comment by daniel-ness** [comment]
Doh, thanks for letting me know. Glad the pkg was of use to someone else
